@host=http://localhost:3003


###
get {{host}}/test-redis HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGEgVGhhbmggVHVhbiIsImVtYWlsIjoiczEyMzQ1NkBnbWFpbC5jb20iLCJpYXQiOjE2OTIzMzIyNzgsImV4cCI6MTY5MjMzOTQ3OH0.BupIQ1bd7xlIlsIlfygkAdbNCbwm7oBaRITOVBDTId91i2kaJR6kP7tItXaujaa1RsaCnM9JwlciUypy8AYc-W90TUQ39_3IqvITloZzWLYT43UrE3lgPvl0fTSpoeVQmnDiunpW5-wsJKfG3fPWZ8gwu4HnCV5XTzem6KeN-njj3cxaVK4_yNuULOe-hBCxkK78vzTmTf7NWC7vzwAmkh5BS0Brk_Z0Urfsg0OalC7rsoIQ9DJDsnBPacpPq6zttN5rJtM5nF6UtVdmM23T4Py2mFhT-GZhcnKru7AibYlSmOsSsSBPA0MxNkTOXHNBBhdiWrWOGisDnPotrx6xaw

###
get {{host}}/test-middleware HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTZhYzMyOTdiOWQ0MDVlZjA3Y2U5YSIsImRldmljZUlkIjoiZmNjNmYzNjZiNWU1YzQ0YjJmYzg0Yjk3Iiwicm9sZSI6W10sImlhdCI6MTY5Mjg3NzAzMiwiZXhwIjoxNjkyODc3MTUyfQ.hju29D8Dy6kuIQQFsHRTdcdVti0JRuOdMQqCpAgXFG5VFhV4uV8C77meGLkJHSeTMs4BItF48u--O_0RKlC_ll4wZuVozKG8bsITwj4O8IePVHzjmXlqWGu2qJ5WAy7yv7oh_2E0zSzPOPQxAfB8_z9RtHoQ3b60IFmNTE1amKLW6DQCEdT21nNTOh0KnVPV_Dk-AjXivbLrNCvrlX5aVqAEt-F478E6v_XWge78JJDUv_P5lqOKNSkqS-viCQ6FjHUF_QPrGqm04OcpWrNpBQSegUGOLRc7bLqY9zCHqI9R4qojjPvRRQPmCLc6w5JmehvhgZn8ZAsBPv6AUQ2Rkw

