# @host = http://localhost:3003

# ###
# GET {{host}}/add-friend/?id=64e08ddfbfc05b4914ea7be6&friendId=jhgffb HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDUyY2NmNjRkOWMyY2M5NDYxYTdlMiIsImRldmljZUlkIjoiNGU1MzZmMzkwZGExMzIxMjA2MDVhYmU5Iiwicm9sZSI6W10sImlhdCI6MTY5NDg0NDA3MCwiZXhwIjoxNjk0ODUxMjcwfQ.DkojzSK-OyfHByLgGspHCGFlK8oRQdXYg5PfM09LMdHxRP27WRGbOcS4h8_wvUF82eqOefhs9tk-VO9jn-7IPVNVilKiDKNIb98j-_k6H4CiJctO4rdqRozgPN44tyQy6i273DUEItmDp21zuDie8cRLHOHdZXmIFpvUaOgFmCHNy_sGcz1CN5MH2EocDJiQH6F48RaYJ_xQWpw_zxJeakEp_1NdUQiubN4dDg4qNi7DE5c2DwXo_xePQZqc6KKAMWpdUSA5LhuyXpzzX5XQkeXFPAZUA7MgZ-BP6Bp9-FZu5cawCYOJYI6KWYd07o9WeveoZ1MIarjqcpeUKVHhZA
