// const socket= {
//     _events: [Object: null prototype] { error: [Function: noop] },
//     _eventsCount: 1,
//     _maxListeners: undefined,

//     nsp: <ref *1> Namespace {
//       _events: [Object: null prototype] { connection: [Function (anonymous)] },
//       _eventsCount: 1,
//       _maxListeners: undefined,
//       sockets: Map(0) {},
//       _fns: [ [Function (anonymous)] ],
//       _ids: 0,
//       server: Server {
//         _events: [Object: null prototype] {},
//         _eventsCount: 0,
//         _maxListeners: undefined,
//         _nsps: [Map],
//         parentNsps: Map(0) {},
//         parentNamespacesFromRegExp: Map(0) {},
//         _path: '/socket.io',
//         clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
//         _connectTimeout: 45000,
//         _serveClient: true,
//         _parser: [Object],
//         encoder: [Encoder],
//         opts: [Object],
//         _adapter: [class Adapter extends EventEmitter],
//         sockets: [Circular *1],
//         eio: [Server],
//         httpServer: [Server],
//         engine: [Server],
//         _corsMiddleware: [Function: corsMiddleware],
//         [Symbol(kCapture)]: false
//       },
//       name: '/',
//       adapter: Adapter {
//         _events: [Object: null prototype] {},
//         _eventsCount: 0,
//         _maxListeners: undefined,
//         nsp: [Circular *1],
//         rooms: Map(0) {},
//         sids: Map(0) {},
//         encoder: [Encoder],
//         [Symbol(kCapture)]: false
//       },
//       [Symbol(kCapture)]: false
//     },
//     client: Client {
//       sockets: Map(0) {},
//       nsps: Map(0) {},
//       server: Server {
//         _events: [Object: null prototype] {},
//         _eventsCount: 0,
//         _maxListeners: undefined,
//         _nsps: [Map],
//         parentNsps: Map(0) {},
//         parentNamespacesFromRegExp: Map(0) {},
//         _path: '/socket.io',
//         clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
//         _connectTimeout: 45000,
//         _serveClient: true,
//         _parser: [Object],
//         encoder: [Encoder],
//         opts: [Object],
//         _adapter: [class Adapter extends EventEmitter],
//         sockets: [Namespace],
//         eio: [Server],
//         httpServer: [Server],
//         engine: [Server],
//         _corsMiddleware: [Function: corsMiddleware],
//         [Symbol(kCapture)]: false
//       },
//       conn: Socket {
//         _events: [Object: null prototype],
//         _eventsCount: 3,
//         _maxListeners: undefined,
//         id: '_llH9IMNDbrkzNPLAAAA',
//         server: [Server],
//         upgrading: true,
//         upgraded: false,
//         _readyState: 'open',
//         writeBuffer: [],
//         packetsFn: [],
//         sentCallbackFn: [],
//         cleanupFn: [Array],
//         request: [IncomingMessage],
//         protocol: 4,
//         remoteAddress: '::1',
//         checkIntervalTimer: null,
//         upgradeTimeoutTimer: Timeout {
//           _idleTimeout: 10000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 1243,
//           _onTimeout: [Function (anonymous)],
//           _timerArgs: undefined,
//           _repeat: null,
//           _destroyed: false,
//           [Symbol(refed)]: true,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 101,
//           [Symbol(triggerId)]: 96
//         },
//         pingTimeoutTimer: Timeout {
//           _idleTimeout: 45000,
//           _idlePrev: [TimersList],
//           _idleNext: [Timeout],
//           _idleStart: 1245,
//           _onTimeout: [Function (anonymous)],
//           _timerArgs: undefined,
//           _repeat: null,
//           _destroyed: false,
//           [Symbol(refed)]: true,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 104,
//           [Symbol(triggerId)]: 103
//         },
//         pingIntervalTimer: Timeout {
//           _idleTimeout: 25000,
//           _idlePrev: [TimersList],
//           _idleNext: [TimersList],
//           _idleStart: 1214,
//           _onTimeout: [Function (anonymous)],
//           _timerArgs: undefined,
//           _repeat: null,
//           _destroyed: false,
//           [Symbol(refed)]: true,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 66,
//           [Symbol(triggerId)]: 0
//         },
//         transport: [Polling],
//         [Symbol(kCapture)]: false
//       },
//       encoder: Encoder { replacer: undefined },
//       decoder: Decoder { reviver: undefined, _callbacks: [Object] },
//       id: '_llH9IMNDbrkzNPLAAAA',
//       onclose: [Function: bound onclose],
//       ondata: [Function: bound ondata],
//       onerror: [Function: bound onerror],
//       ondecoded: [Function: bound ondecoded],
//       connectTimeout: Timeout {
//         _idleTimeout: 45000,
//         _idlePrev: [Timeout],
//         _idleNext: [TimersList],
//         _idleStart: 1219,
//         _onTimeout: [Function (anonymous)],
//         _timerArgs: undefined,
//         _repeat: null,
//         _destroyed: false,
//         [Symbol(refed)]: true,
//         [Symbol(kHasPrimitive)]: false,
//         [Symbol(asyncId)]: 69,
//         [Symbol(triggerId)]: 0
//       }
//     },
//     recovered: false,
//     data: {},
//     connected: false,
//     acks: Map(0) {},
//     fns: [],
//     flags: {},
//     server: <ref *2> Server {
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       _nsps: Map(1) { '/' => [Namespace] },
//       parentNsps: Map(0) {},
//       parentNamespacesFromRegExp: Map(0) {},
//       _path: '/socket.io',
//       clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
//       _connectTimeout: 45000,
//       _serveClient: true,
//       _parser: {
//         protocol: 5,
//         PacketType: [Object],
//         Encoder: [class Encoder],
//         Decoder: [class Decoder extends Emitter]
//       },
//       encoder: Encoder { replacer: undefined },
//       opts: { cors: [Object], cleanupEmptyChildNamespaces: false },
//       _adapter: [class Adapter extends EventEmitter],
//       sockets: <ref *1> Namespace {
//         _events: [Object: null prototype],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         sockets: Map(0) {},
//         _fns: [Array],
//         _ids: 0,
//         server: [Circular *2],
//         name: '/',
//         adapter: [Adapter],
//         [Symbol(kCapture)]: false
//       },
//       eio: Server {
//         _events: [Object: null prototype],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         middlewares: [Array],
//         clients: [Object],
//         clientsCount: 1,
//         opts: [Object],
//         ws: [WebSocketServer],
//         [Symbol(kCapture)]: false
//       },
//       httpServer: Server {
//         maxHeaderSize: undefined,
//         insecureHTTPParser: undefined,
//         requestTimeout: 300000,
//         headersTimeout: 60000,
//         keepAliveTimeout: 5000,
//         connectionsCheckingInterval: 30000,
//         joinDuplicateHeaders: undefined,
//         rejectNonStandardBodyWrites: false,
//         _events: [Object: null prototype],
//         _eventsCount: 5,
//         _maxListeners: undefined,
//         _connections: 2,
//         _handle: [TCP],
//         _usingWorkers: false,
//         _workers: [],
//         _unref: false,
//         allowHalfOpen: true,
//         pauseOnConnect: false,
//         noDelay: true,
//         keepAlive: false,
//         keepAliveInitialDelay: 0,
//         highWaterMark: 16384,
//         httpAllowHalfOpen: false,
//         timeout: 0,
//         maxHeadersCount: null,
//         maxRequestsPerSocket: 0,
//         _connectionKey: '6::::3003',
//         [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//         [Symbol(ServerResponse)]: [Function: ServerResponse],
//         [Symbol(kCapture)]: false,
//         [Symbol(async_id_symbol)]: 15,
//         [Symbol(http.server.connections)]: ConnectionsList {},
//         [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//           _idleTimeout: 30000,
//           _idlePrev: [Timeout],
//           _idleNext: [TimersList],
//           _idleStart: 832,
//           _onTimeout: [Function: bound checkConnections],
//           _timerArgs: undefined,
//           _repeat: 30000,
//           _destroyed: false,
//           [Symbol(refed)]: false,
//           [Symbol(kHasPrimitive)]: false,
//           [Symbol(asyncId)]: 13,
//           [Symbol(triggerId)]: 1
//         },
//         [Symbol(kUniqueHeaders)]: null
//       },
//       engine: Server {
//         _events: [Object: null prototype],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         middlewares: [Array],
//         clients: [Object],
//         clientsCount: 1,
//         opts: [Object],
//         ws: [WebSocketServer],
//         [Symbol(kCapture)]: false
//       },
//       _corsMiddleware: [Function: corsMiddleware],
//       [Symbol(kCapture)]: false
//     },
//     adapter: <ref *3> Adapter {
//       _events: [Object: null prototype] {},
//       _eventsCount: 0,
//       _maxListeners: undefined,
//       nsp: <ref *1> Namespace {
//         _events: [Object: null prototype],
//         _eventsCount: 1,
//         _maxListeners: undefined,
//         sockets: Map(0) {},
//         _fns: [Array],
//         _ids: 0,
//         server: [Server],
//         name: '/',
//         adapter: [Circular *3],
//         [Symbol(kCapture)]: false
//       },
//       rooms: Map(0) {},
//       sids: Map(0) {},
//       encoder: Encoder { replacer: undefined },
//       [Symbol(kCapture)]: false
//     },
//     id: 'CsBD3nobmhgl326XAAAB',
//     handshake: {
//       headers: {
//         host: 'localhost:3003',
//         connection: 'keep-alive',
//         'sec-ch-ua': '"Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"',
//         accept: '*/*',
//         'sec-ch-ua-mobile': '?0',
//         'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36',
//         'sec-ch-ua-platform': '"Windows"',
//         origin: 'http://localhost:3000',
//         'sec-fetch-site': 'same-site',
//         'sec-fetch-mode': 'cors',
//         'sec-fetch-dest': 'empty',
//         referer: 'http://localhost:3000/',
//         'accept-encoding': 'gzip, deflate, br',
//         'accept-language': 'en-US,en;q=0.9,vi-VN;q=0.8,vi;q=0.7,fr-FR;q=0.6,fr;q=0.5'
//       },
//       time: 'Tue Aug 22 2023 16:48:43 GMT+0700 (Indochina Time)',
//       address: '::1',
//       xdomain: true,
//       secure: false,
//       issued: 1692697723334,
//       url: '/socket.io/?EIO=4&transport=polling&t=OeSfO6Q',
//       query: [Object: null prototype] {
//         EIO: '4',
//         transport: 'polling',
//         t: 'OeSfO6Q'
//       },
//       auth: {}
//     },
//     [Symbol(kCapture)]: false
//   }