@host = http://localhost:3003



# tokeTuan: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDc1NWFiZjg2MGMxZmEzYTMwZSIsImRldmljZUlkIjoiZjk3OWIzNjljNjk0MjgxNjc0NjI1MGI4Iiwicm9sZSI6W10sImlhdCI6MTY5NjQwODE3NywiZXhwIjoxNjk2NDE1Mzc3fQ.SxrH44HqmqIUUzVs1HgWpA6yVHYBf-QKE3MqgUx8AXM7ESb0yYGe42oMvtmN5l6VcyABiBAr00dPuq_1mg62I5HHaHGE6RsVh2pOsgUE8MWIw3deeVp9QJ90YGoHxlyyRUsaHUqOOjF8D1XrpGBOpdQvvDmeKfps6-p7Qe85CS5_zCjUf4V32wGxCKKV55UT4tzW-rvWXkQQ5Qw0CwDfPCICUptuYbWPISFdIJywK_JahgzSF6FWJsZMPxq23vjOj59Tfc7Ta8-DttI6oRn5TYBd476B2qvtyveb9dusmMEm3DM8sYPZC3H71GJSyVniWN6GdmFZcE6Z6QMJCjZizA

# tokeTien: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDhmNWFiZjg2MGMxZmEzYTMxNCIsImRldmljZUlkIjoiOTc5YjM2OWM2OTQyODE2NzQ2MjUwYjg1Iiwicm9sZSI6W10sImlhdCI6MTY5NjQwODIwNywiZXhwIjoxNjk2NDE1NDA3fQ.cLdLly8kE8gb5OATISqY0NBOnjlM4s6bR5utknbejO-jRa31t9Uqec_3soLgtVmMrrzKtxN3Nf9mRg8Qe1F-HQ_7SpUPqkdTgdHl-8GiCDW4ulNtT9q8nEeoGzItgpy4kYorNoIYAK7jrXsGz6UlFMtWQAEPihUNuN2WYBDsDQzYZ8MlMy-mMgIwVgpCKWwPqktATglFb0AhX7J7y5KNr_W64ZmyYSqF4C14mQma1jXMUYWIOJg3gfZQBrACROqo6T3uLRkBtbGKhjVuCmstvqtLq-WSCJHTYCis6tFYEN7ZfnqVWATR-mBZnEJn6YJBScfg-mQzMs72IKbuWOgKjw

# tokeToan: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDgzNWFiZjg2MGMxZmEzYTMxMSIsImRldmljZUlkIjoiNzliMzY5YzY5NDI4MTY3NDYyNTBiODU3Iiwicm9sZSI6W10sImlhdCI6MTY5NjQwODI0NCwiZXhwIjoxNjk2NDE1NDQ0fQ.eb3Cl9gZH3iwakRhWoR9naCzWiqqqA-iGLZGQJJ0Na4eQhb1Bje5Z30aVcHT63FpZJynWHAe2hXEeGIVSnok8JjnKZDb3WLC383nLyAjyHb02jwFbYbQa6ENerkL3w3qHduwB42Ds370Q83wM78dNdf2v9sHebUEhEcG0nyvd1Sqp1-PBbyL15qtPrLPZoV1Pj5BR0hs5VXNfrIYnyDpjjcd25ycgs_OQAF8V9pLGTfVh2ifDmQJiunI6GXVDY7jupD6Tj0u1VnzRxBjW6VH7QzhhkDMkENQ-YMr2_Q0Yi2Rw0SuvksnGyvQYZE1bXXaCufs2zLkx-lq6t8Bjm8E8w
###
POST {{host}}/authentication/sign-up HTTP/1.1
content-type: application/json

{
    "name": "Nguyen Thi Tham Luon",
    "email": "s2NguyenThiThamLuon2s@gmail.com",
    "password": "123456789"
}   


###
POST {{host}}/authentication/sign-in HTTP/1.1
content-type: application/json

{
    # "email": "s2hathanhtien2s@gmail.com",
    "email": "s2hathanhtuan2s@gmail.com",
    # "email": "s2hathanhtoan2s@gmail.com",
    "password": "123456789"
}

###
POST {{host}}/authentication/sign-out HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTZhYzMyOTdiOWQ0MDVlZjA3Y2U5YSIsImRldmljZUlkIjoiZDJjYTY3ODE5MDE4MmJhMWRkZWJjZDRmIiwicm9sZSI6W10sImlhdCI6MTY5Mjg4MjI1MiwiZXhwIjoxNjkyODgyMzcyfQ.H1K-KSLmIaaffQoCSN7HYrkBbGe3K_kZMMaUv0QuvSeTSZ777ZwZ2hvhj6ax8CEhuGJ6ThVSSMJmFMpFtyUxqIyIZ5o83Apwkw8I-894u1sfry5n4Wyes63AANm-yv06fepwdxcD1YJ9DxzlN_kpJfGCiJvi5a_NGTTjiFCLrMwO8-TqkGPeyf58y9Vf-R4z9-lNdXvKC-tyZ-HUiN1o2E5TvW2XYYjdk_J9MAGVstN2AHcbD6bHP4djPHW1suPAQpJQ11v2CcBd_tV5GgWdur7C1GpqrnVQuVQ99cFX4aFpmaQyBlCIafOuiQEWAAeNefvlg5Cwy_C58U36pk54mg

###
POST {{host}}/authentication/refresh-token HTTP/1.1
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTZhYzMyOTdiOWQ0MDVlZjA3Y2U5YSIsImRldmljZUlkIjoiZmNjNmYzNjZiNWU1YzQ0YjJmYzg0Yjk3Iiwicm9sZSI6W10sImlhdCI6MTY5Mjg3NjkyMSwiZXhwIjoxNjkyODc3MTYxfQ.hTKGiFoz0rT5OITxwdxaWo_pFI8Sc4NJCI7LCGzX3NLb0X2DZismMSKoiBM59GEmRoOLOpZHJWQ1cXObHkX5HPLJSxCb3obDOVH_SwenmHCICNsy34N17Sv5EjaLghNTFkzQRK3qR1EEC1hP6390-UUw776BhbvssUv5mvQW78ZRE_9K_-DBAzbKFTiqnlLsKFuh9W0wIc2X-1CZx6PazzNlmzdvk9KLzwr8HZ6jy-xhPaPAR1xhs9o0v8uLdyNxPrwKe04lnqWneJWIUg2PXk__IX0menTyLnj6QtKBBAOVJ-fCsSioVX2WPrGfNrXPpD90YmieU2kvYArpNdpm0g"
} 
