@host = http://localhost:3003

###

POST {{host}}/chat/conversation HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDc1NWFiZjg2MGMxZmEzYTMwZSIsImRldmljZUlkIjoiNmRiODlkM2YwNWU4NjIxZWM0NjhmMmIzIiwicm9sZSI6W10sImlhdCI6MTY5NTcyMTk1MSwiZXhwIjoxNjk1NzI5MTUxfQ.XypWxm6tB8OLoD10jheNGZzWW2It1_i54AkB5JnFMZ7DXGF-gQLwFRueNodQKAyvJshsGJLvoP05g1KG0Zr57BQ5O9B7UVwUuNwADz6Uikc3bTmWlwkdYgOkgbR25lrBvWURckVlbb3u3vrAtMIsfYvf3lupH0FY6crzfk1IMAH8zWFKXKwNxE912vy6xqL3hH5Mltq-slvb-j0U540Pg3p-QJyBgBJbYMQcN6yXqAGFEjk3OUgF0Sp56_D-RFBc_xE6yYEXO8IumiHqmKdakQ_osRBHa4XiKh4kh0tGeG-U4BuGU0PynB00m0XVJ3FLsYvHTMRfYEYA3aRiSilqhg

{
    "members": ["650fe4835abf860c1fa3a311","650fe4835abf860c1fa3a311"]
}


###
GET  {{host}}/chat/test HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTdiNWQzNTIyOWIxNTY3MzY2ODMwNCIsImRldmljZUlkIjoiY2Q0YThhMTVjZTBmNjc4ZWVhYmMyZjVjIiwicm9sZSI6W10sImlhdCI6MTY5MzUzNDk2MiwiZXhwIjoxNjkzNTQyMTYyfQ.Zf9Gs6W82yqDMJ9mEiM8Ec5YD4CBcVnqJg3XjzJfpP_TsQgcp9DZV8nT-7xzySmcpod3-JTKxejJttGflxzTLnyDWUBffE_j4PbZd_C0bIufvxDSXckj4ubn8cLltFRawhmBpgti-OgC6_ipfmzyIVNHpLPuwQ73kOj9-j9vWNKmZ7zV_ZRmjchan0RpDi7aYwF1eSbsbaKlrNHWYSiqZIAgmLQISvywcdiq5SuClmrwJnHtXDI0HRF0qJDuzxeK4wc9_d1PAqUNfzECshFrq0vMovXLGGmQrrWs-LWBSddE_dIWmnAXFDCaS_eGIxt4TtM43me5Fq9YrC_FBYaCbA


# ###
# GET  {{host}}/chat/get-conversations-message/64f0040caf7513894811e559 HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTg1MWQzODExMzFjNmJhMDdlMTU2YSIsImRldmljZUlkIjoiOTI1MGFiM2E0Nzk1MTQ2N2RkNTZmNmY3Iiwicm9sZSI6W10sImlhdCI6MTY5MzYzMjE1OSwiZXhwIjoxNjkzNjM5MzU5fQ.Pod6jB3YV2O0K8g_WtIA-PhyMbah_HEIqb9XfoMzBlD8-tmxApBsGy5fvyeGZ2HljleqINd8RFLDLhP9gb4Gw7eNNgaIiEvvc0l_fyT0NeNnX6uaPeFuZ8uHD4awPzy07_hsTyrYw46wRxm0Fx_GIbsvK5Jgk5oJurkw9sNw2b-SkQFLYjBYTlr4KUlEag5bd8jwZfftWNOPthJNut5_rx0ycuRPkxgu3xreoGMgdKz-PeeSW9lFPTam_jUi-1YItrAinnBbvaGiFwWu4nRGcxB7yr6J8BPsGBiBH_P5-x3YFzfb1j6O7Is4n0sO65jNMcu_e8-tKBa_x1lnpl4iAw

# ### 

# POST  {{host}}/chat/request-conversation HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDUyZDA1NjRkOWMyY2M5NDYxYTdlYiIsImRldmljZUlkIjoiMjFiZTMyZjRmNTIzZTAwY2JhMGRkMmZkIiwicm9sZSI6W10sImlhdCI6MTY5NDgzODAyMiwiZXhwIjoxNjk0ODQ1MjIyfQ.GYJbTqKqc-HJ0HX7TUQSdF3ILdZbC5JIvBEgwGIKFriM-IIwKD-cfxGGbhs0dW7G6QEp0jSPhSRMhRkCHkEaejYAiCaTZpZ5qOlEzJ-DMA5jWmehFKi7fXO05KhMursjIO5jfNRQB37uwo7KULTvEamI7eYTMtDO-dPioS_Ec-D50K27ieGgV6n5_7xlwfjS3XSc55LS0Wx2u6-q-SP9GtDdFom4KcnrDpWbUjni529qsBlHWLN-FJk2c0SBHCJQGvQj0ai5qkM6kf7DZGPv6ylZ7G3TWo-2Bz6m_zMHfp7VMk7MnDGy1Wcu9Y2LZmvjIMyLY13Tn1zQfgKKQ3RFfg

# {

#     "userId": "650488c3d2121c21cbc88f83",
#     "receiverId": "6504890dd2121c21cbc88f86"
# }

##

