@host = http://localhost:3003



# tokeTuan: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDc1NWFiZjg2MGMxZmEzYTMwZSIsImRldmljZUlkIjoiZjk3OWIzNjljNjk0MjgxNjc0NjI1MGI4Iiwicm9sZSI6W10sImlhdCI6MTY5NjQwODE3NywiZXhwIjoxNjk2NDE1Mzc3fQ.SxrH44HqmqIUUzVs1HgWpA6yVHYBf-QKE3MqgUx8AXM7ESb0yYGe42oMvtmN5l6VcyABiBAr00dPuq_1mg62I5HHaHGE6RsVh2pOsgUE8MWIw3deeVp9QJ90YGoHxlyyRUsaHUqOOjF8D1XrpGBOpdQvvDmeKfps6-p7Qe85CS5_zCjUf4V32wGxCKKV55UT4tzW-rvWXkQQ5Qw0CwDfPCICUptuYbWPISFdIJywK_JahgzSF6FWJsZMPxq23vjOj59Tfc7Ta8-DttI6oRn5TYBd476B2qvtyveb9dusmMEm3DM8sYPZC3H71GJSyVniWN6GdmFZcE6Z6QMJCjZizA
# tokeTien: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDhmNWFiZjg2MGMxZmEzYTMxNCIsImRldmljZUlkIjoiOTc5YjM2OWM2OTQyODE2NzQ2MjUwYjg1Iiwicm9sZSI6W10sImlhdCI6MTY5NjQwODIwNywiZXhwIjoxNjk2NDE1NDA3fQ.cLdLly8kE8gb5OATISqY0NBOnjlM4s6bR5utknbejO-jRa31t9Uqec_3soLgtVmMrrzKtxN3Nf9mRg8Qe1F-HQ_7SpUPqkdTgdHl-8GiCDW4ulNtT9q8nEeoGzItgpy4kYorNoIYAK7jrXsGz6UlFMtWQAEPihUNuN2WYBDsDQzYZ8MlMy-mMgIwVgpCKWwPqktATglFb0AhX7J7y5KNr_W64ZmyYSqF4C14mQma1jXMUYWIOJg3gfZQBrACROqo6T3uLRkBtbGKhjVuCmstvqtLq-WSCJHTYCis6tFYEN7ZfnqVWATR-mBZnEJn6YJBScfg-mQzMs72IKbuWOgKjw
# tokeToan: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDgzNWFiZjg2MGMxZmEzYTMxMSIsImRldmljZUlkIjoiNzliMzY5YzY5NDI4MTY3NDYyNTBiODU3Iiwicm9sZSI6W10sImlhdCI6MTY5NjQwODI0NCwiZXhwIjoxNjk2NDE1NDQ0fQ.eb3Cl9gZH3iwakRhWoR9naCzWiqqqA-iGLZGQJJ0Na4eQhb1Bje5Z30aVcHT63FpZJynWHAe2hXEeGIVSnok8JjnKZDb3WLC383nLyAjyHb02jwFbYbQa6ENerkL3w3qHduwB42Ds370Q83wM78dNdf2v9sHebUEhEcG0nyvd1Sqp1-PBbyL15qtPrLPZoV1Pj5BR0hs5VXNfrIYnyDpjjcd25ycgs_OQAF8V9pLGTfVh2ifDmQJiunI6GXVDY7jupD6Tj0u1VnzRxBjW6VH7QzhhkDMkENQ-YMr2_Q0Yi2Rw0SuvksnGyvQYZE1bXXaCufs2zLkx-lq6t8Bjm8E8w

###

POST {{host}}/friend/unfriend/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDgzNWFiZjg2MGMxZmEzYTMxMSIsImRldmljZUlkIjoiNmM3YjE4ZDY3OWUzYTk2ZWM0ODI1MzMzIiwicm9sZSI6W10sImlhdCI6MTY5NTY0NjY4NiwiZXhwIjoxNjk1NjUzODg2fQ.oR3Z1JNlYHZ6ebINsP6us7-X8HYuMAC34m-tEO1LMKVuq9rk9_IY7fBAKpUCH8lASgM5QhLn0DEvHpHivPqJcHXjxJH-U828-0IgvavymDyKRh4UtZ-JmoRUojVkTuVT8t481C7giyZWbRMiW8SqeoBq7T4UbxxeieZhE4P4vRxBCZt8PdWG0_XOlfIe9telJ-7lcxLC2NK5L7yJYGLnhnEX0OjT7mXMCh5YU7dgB7pU1jziwcUTOodoHTWGaq-QwNDTvj6AaJRkER6HWz5CRCDzHO_MjeOyxK6S-dgS2ZivmCFwxYKlJXeYYHGRoplYI_2I5OUBaLGVLFtNueUPKA

{
    "friendId":"650fe4755abf860c1fa3a30e"
}

###
POST {{host}}/friend/accept-request-friend/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDhmNWFiZjg2MGMxZmEzYTMxNCIsImRldmljZUlkIjoiOTc5YjM2OWM2OTQyODE2NzQ2MjUwYjg1Iiwicm9sZSI6W10sImlhdCI6MTY5NjQwODIwNywiZXhwIjoxNjk2NDE1NDA3fQ.cLdLly8kE8gb5OATISqY0NBOnjlM4s6bR5utknbejO-jRa31t9Uqec_3soLgtVmMrrzKtxN3Nf9mRg8Qe1F-HQ_7SpUPqkdTgdHl-8GiCDW4ulNtT9q8nEeoGzItgpy4kYorNoIYAK7jrXsGz6UlFMtWQAEPihUNuN2WYBDsDQzYZ8MlMy-mMgIwVgpCKWwPqktATglFb0AhX7J7y5KNr_W64ZmyYSqF4C14mQma1jXMUYWIOJg3gfZQBrACROqo6T3uLRkBtbGKhjVuCmstvqtLq-WSCJHTYCis6tFYEN7ZfnqVWATR-mBZnEJn6YJBScfg-mQzMs72IKbuWOgKjw


{
    "requestFriendId":"65128df3efa67d3106cc011b"
}

###
POST {{host}}/friend/reject-request-friend/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDgzNWFiZjg2MGMxZmEzYTMxMSIsImRldmljZUlkIjoiNDUyOTE3OTBkMWJkN2FhMWVhZThjNmZjIiwicm9sZSI6W10sImlhdCI6MTY5NTYzODQ4NywiZXhwIjoxNjk1NjQ1Njg3fQ.E0tGbmncZ3z82_eSeEziG3qpwYR9L0y3E3I8nfDMD4Err4w4Z7FSdT44GNQDH5fpkyK_LwbaWHaPoWSQyUaTsB-jdreQ0DJac2Wpw7VN-cJIcJN8LOL0njI_79t4gAFaX1rc7qmV3Y-Pc8CEyz4jQPWTy4LTlk9_jHSmoOy6H91NI5SeCgqJ82eZngU0bccyQjfmqsp7BxZ_Wo402tAhM_Li3YtstWnYpTmcZahBcWEIdTTn-txe-9N3ksZSIescfB-FiTwx0NXPfvRBbNpRQkrGn2CHWF7dwRi6-s91pWpeWFBhO3cCe9v0mH4xm8Hd1I7iMGYpMQAzK-kmJp31YQ

{
    "requestFriendId":"65117a3f9e3eb625d2c63de5"
}

###
POST {{host}}/friend/request-friend/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDc1NWFiZjg2MGMxZmEzYTMwZSIsImRldmljZUlkIjoiMWMyYmI5ZjE0ZGYzYjJkNjdhN2IzNjcwIiwicm9sZSI6W10sImlhdCI6MTY5Njc0Mjk3MSwiZXhwIjoxNjk2NzUwMTcxfQ.cuNnK7QGhrT2CCmec5scVn5JBFgg9RExVr429q3Vz6FRmO2jfUBQDqHMYCa5qvI2pzCJVzexmVSM-6Tduyz9o7GcMUab29P7YZoUhEkReWrjRkUpV8_fPQW5dcn69K9Z4094PwBScjSphU4xJXtlBPYSiGKiChtIpbxNnt3QlZugwBl1eTkq5M8jzbbvUNLKmC0l4E1-EGLjZnTw96lvbai2jE95puq0fdVtbB2CKN6MNur1iQjqQSz6l6i172tDVrZTsnzl6crc_YcmEFsOujtrOdgesUCXc6HUIxg84-CNml404QSfM4-7Tft0ee4sgaKPLJ2LIRIVlIcRi0eiVg


{
    "receiverId":"65223de704999e9482e3b502"
    # "receiverId":"650fe4835abf860c1fa3a311"
}

###
DELETE {{host}}/friend/request-friend/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDc1NWFiZjg2MGMxZmEzYTMwZSIsImRldmljZUlkIjoiMDQ1MjkxNzkwZDFiZDdhYTFlYWU4YzZmIiwicm9sZSI6W10sImlhdCI6MTY5NTYzODQ0NCwiZXhwIjoxNjk1NjQ1NjQ0fQ.Hcl6r3v5SSiFU3ozGCEDmEyCuW1brvvpn9ar6jXgHu0_ej-SN2VV-nHpyi4wTvdegO63nMpeqr7XFjVSuK8-S37x_3PaONYYXEzu8nlJ7JOyNQ_ZkAP8laxFTZ3FPk1TMKEPXFbeXBBNw7g_HGbnASS1lZkbDgxPAajqGP3Gql1Gf8-CPZ7nLrP1VE_n-lr86wSIFcT_CqRL5JLii5rocRDrePqfxuAWn4iYtbA8PzFfGDh5yPtWlvTClF06UAjeqFU-u2oqIEdfikwO2GxHP36sliNNEn3H8JN0oCfKw1bwMOXRXHGFA-xKzBamYBGZ2sJdOKiNPz_ipU4R-Bhm6g

{
    "requestFriendId":"65117a729e3eb625d2c63df0"
}

//Tham 65223de704999e9482e3b502
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjIzZGU3MDQ5OTllOTQ4MmUzYjUwMiIsImRldmljZUlkIjoiYzFjMmJiOWYxNGRmM2IyZDY3YTdiMzY3Iiwicm9sZSI6W10sImlhdCI6MTY5Njc0Mjg4NywiZXhwIjoxNjk2NzUwMDg3fQ.ZRh_ATxQavnPz8Nzp-vF0wx_P0OCwpURLqV8oXYVjTMMrwfid5Yi_zR3iNIRllOE8rJna6qGnczQIi7iEgSt9aDdK3e6dRGbeC_Lr4wila1iEVq1Z_VOXwdfpJb-GrePoPkv4DbPpc8KZB_nacq9A0mexYn9IWoXHmOQL4p_Fnq6WpxYeK6Lgm1hAI54IhKQ0PFYM2CmFWqdx9XXzYXatQd1ARmVfukMChYxEPdktyCI_jgM2AH2wPJs1uCUMf5LDXaGJbsIG-hhO68xDYtRp2PUG8EEAjhBadbkePAtLzlDNP-JOmVYSzaA_h4tB0mO11RQWknSyfLwUU20RZ6L7g

//Tuan 650fe4755abf860c1fa3a30e
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MGZlNDc1NWFiZjg2MGMxZmEzYTMwZSIsImRldmljZUlkIjoiMWMyYmI5ZjE0ZGYzYjJkNjdhN2IzNjcwIiwicm9sZSI6W10sImlhdCI6MTY5Njc0Mjk3MSwiZXhwIjoxNjk2NzUwMTcxfQ.cuNnK7QGhrT2CCmec5scVn5JBFgg9RExVr429q3Vz6FRmO2jfUBQDqHMYCa5qvI2pzCJVzexmVSM-6Tduyz9o7GcMUab29P7YZoUhEkReWrjRkUpV8_fPQW5dcn69K9Z4094PwBScjSphU4xJXtlBPYSiGKiChtIpbxNnt3QlZugwBl1eTkq5M8jzbbvUNLKmC0l4E1-EGLjZnTw96lvbai2jE95puq0fdVtbB2CKN6MNur1iQjqQSz6l6i172tDVrZTsnzl6crc_YcmEFsOujtrOdgesUCXc6HUIxg84-CNml404QSfM4-7Tft0ee4sgaKPLJ2LIRIVlIcRi0eiVg

//Tham Luon 65223e6504999e9482e3b506
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjIzZTY1MDQ5OTllOTQ4MmUzYjUwNiIsImRldmljZUlkIjoiYzJiYjlmMTRkZjNiMmQ2N2E3YjM2NzA4Iiwicm9sZSI6W10sImlhdCI6MTY5Njc0MzAxMywiZXhwIjoxNjk2NzUwMjEzfQ.McJX-RAmN5GCxIsH3FNc6QlHeYI5rODdybBtk33z2VjGn0Y-rHamKt3je0X4QtBWHbK2sw9zLSi-QPFSRSg0K2Wz5NNIlWpEGz1DlWLUXOlIf6P5kOPPYS2VMmQH3_M8LMew3x3DEyALmmZBIo_mUClJY9cO_Xs0hXbKQcwhVG2XPWAQMlWPEqyHR2JUXhAHcHnGLza10w6PnzN-hJygrxeSiuRUbZqVrKLwUzuDhnJMCn2TcvUMD5lmk1dWnkDxH6hios8sGdn4L6zs5atCnVVX729C8WNerTuC17NYPnB_BkQ_pIaaO9YdgWAYjejWqQflLLVCeuIKU1rLLHPekg